### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by WebShapedBiz** [daftspunk/oc-formist-plugin#1]
Hello and thank you for your effort in providing us with really useful tutorials.

Unfortunately with this plugin I have a problem. Whether I use logout/login, `php artisan plugin:refresh acme.formist` or `php artisan october:up` I always end up with the same error message:

> [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'Faker\Factory' not found 

Since I have no composer.json in my root I don't know where and how to add Faker.

Cheers.

Edit: I do have all the tables created in the database.

**Comment by chrisvidal** [comment]
you can install the plugin Faker before installing this formist plugin

**Comment by daftspunk** [comment]
Added to the readme.
